apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name:  local-lab 
  namespace:  argocd
spec:  
  project:  default
  source:  
    repoURL: https://github.com/andrescollazosc/lab-06-argocd-helm/
    targetRevision:  HEAD
    path:  app-06
    helm:
      releaseName: testapp
      valueFiles:
        - secrets.yaml
        - values.yaml
        # - secrets://secrets.yaml
        # - secrets+gpg-import-kubernetes://argocd/helm-secrets-private-keys#poc-key.asc?secrets.yaml

        # - secrets+gpg-import:///helm-secrets-private-keys/poc-key.asc?secrets.yaml
  destination:  
    server:  https://kubernetes.default.svc
    namespace:  testapp
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true